from io import BytesIO

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate

from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.prediction import Prediction

router = APIRouter(
    prefix="/reports",
    tags=["PDF Reports"],
)


@router.get("/{prediction_id}/pdf")
def download_pdf(
    prediction_id: int,
    db: Session = Depends(get_db),
):

    prediction = (
        db.query(Prediction)
        .filter(Prediction.id == prediction_id)
        .first()
    )

    if prediction is None:
        raise HTTPException(
            status_code=404,
            detail="Prediction not found"
        )

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>PreStrokeNet</b>", styles["Title"]))
    story.append(Paragraph("Stroke Prediction Report", styles["Heading2"]))
    story.append(Paragraph("<br/>", styles["BodyText"]))

    story.append(Paragraph(f"<b>Patient Name:</b> {prediction.patient_name}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Patient ID:</b> {prediction.patient_id}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Age:</b> {prediction.age}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Risk Level:</b> {prediction.risk}", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["BodyText"]))

    story.append(
        Paragraph(
            f"<b>Clinical Probability:</b> {prediction.clinical_probability:.2%}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Keystroke Probability:</b> {prediction.keystroke_probability:.2%}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Final Probability:</b> {prediction.final_probability:.2%}",
            styles["BodyText"],
        )
    )

    story.append(Paragraph("<br/>", styles["BodyText"]))

    story.append(
        Paragraph(
            "This report is generated by the PreStrokeNet AI system and is intended to support, not replace, clinical judgment.",
            styles["BodyText"],
        )
    )

    doc.build(story)

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="Prediction_{prediction.id}.pdf"'
        },
    )